openapi: 3.0.1
info:
  title: Provys Catalogue repository Api
  description: Provides methods for accessing entities and other objects from provys
    metadata catalogue
  version: "1.0"
servers:
- url: /api
  variables: {}
paths:
  /attr/{entityNm}/{nameNm}:
    get:
      summary: Get Attribute by Internal Name
      description: Retrieve attribute using internal name
      operationId: getAttrByNameNm
      parameters:
      - name: entityNm
        in: path
        required: true
        schema:
          type: string
      - name: nameNm
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Attribute
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Attr'
  /attr/{attrId}:
    get:
      summary: Get Attribute
      description: Retrieve atribute using Id
      operationId: getAttrById
      parameters:
      - name: attrId
        in: path
        required: true
        schema:
          type: integer
      responses:
        default:
          description: Attribute
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Attr'
  /domain/{domainId}:
    get:
      summary: Get Domain
      description: Retrieve domain using Id
      operationId: getDomainById
      parameters:
      - name: domainId
        in: path
        required: true
        schema:
          type: integer
      responses:
        default:
          description: Domain
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Domain'
  /domain/{domainNm}:
    get:
      summary: Get Domain by Internal Name
      description: Retrieve domain using internal name
      operationId: getDomainByNameNm
      parameters:
      - name: domainNm
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Domain
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Domain'
  /entity/{entityNm}:
    get:
      summary: Get Entity by Internal Name
      description: Retrieve entity using internal name
      operationId: getEntityByNameNm
      parameters:
      - name: entityNm
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Entity
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Entity'
  /entity/{entityId}:
    get:
      summary: Get Entity
      description: Retrieve entity using Id
      operationId: getEntityByNameNm_1
      parameters:
      - name: entityId
        in: path
        required: true
        schema:
          type: integer
      responses:
        default:
          description: Entity
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Entity'
components:
  schemas:
    Attr:
      type: object
      properties:
        name:
          type: string
        entity:
          $ref: '#/components/schemas/Entity'
        javaName:
          type: string
        attrGrp:
          $ref: '#/components/schemas/AttrGrp'
        nameNm:
          type: string
        domain:
          $ref: '#/components/schemas/Domain'
        attrGrpId:
          type: integer
        ord:
          type: integer
          format: int32
        attrType:
          type: string
          enum:
          - COLUMN
          - TEXT
          - FREE
          - FINANCE
          - SQL
          - FORMULA
        properNameRoot:
          type: string
        defValue:
          type: string
        ordInEntity:
          type: integer
          format: int32
        mandatory:
          type: boolean
        entityId:
          type: integer
        subdomainNm:
          type: string
        note:
          type: string
        id:
          type: integer
    AttrGrp:
      type: object
      properties:
        name:
          type: string
        attrs:
          type: array
          items:
            $ref: '#/components/schemas/Attr'
        entity:
          $ref: '#/components/schemas/Entity'
        nameNm:
          type: string
        ord:
          type: integer
          format: int32
        entityId:
          type: integer
        note:
          type: string
        id:
          type: integer
    Domain:
      type: object
      properties:
        name:
          type: string
        lformatCd:
          type: string
        natOrder:
          type: boolean
        allowed:
          type: boolean
        dataTypeNm:
          type: string
        dataLength:
          type: integer
          format: int32
        dataPrecision:
          type: integer
          format: int32
        qvisible:
          type: boolean
        lvisible:
          type: boolean
        validateCd:
          type: string
        note:
          type: string
        nameNm:
          type: string
        id:
          type: integer
    Entity:
      type: object
      properties:
        name:
          type: string
        table:
          type: string
        ancestor:
          $ref: '#/components/schemas/Entity'
        implDoc:
          type: string
        fpPackage:
          type: string
        used:
          type: boolean
        ancestorId:
          type: integer
        behaviourDoc:
          type: string
        objectClass:
          type: boolean
        cpPackage:
          type: string
        custom:
          type: boolean
        usageDoc:
          type: string
        attrGrps:
          type: array
          items:
            $ref: '#/components/schemas/AttrGrp'
        epPackage:
          type: string
        entityGrp:
          $ref: '#/components/schemas/EntityGrp'
        attrs:
          type: array
          items:
            $ref: '#/components/schemas/Attr'
        entityGrpId:
          type: integer
        view:
          type: string
        pgPackage:
          type: string
        customNote:
          type: string
        structureDoc:
          type: string
        note:
          type: string
        nameNm:
          type: string
        id:
          type: integer
    EntityGrp:
      type: object
      properties:
        name:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/EntityGrp'
        fullOrd:
          type: array
          items:
            type: integer
            format: int32
        entities:
          type: array
          items:
            $ref: '#/components/schemas/Entity'
        parentId:
          type: integer
        ord:
          type: integer
          format: int32
        note:
          type: string
        nameNm:
          type: string
        id:
          type: integer
