openapi: 3.0.1
info:
  title: Provys Catalogue repository Api
  description: Provides methods for accessing entities and other objects from provys
    metadata catalogue
  version: "1.0"
servers:
- url: /api
  variables: {}
paths:
  /attr/{entityNm}/{nameNm}:
    get:
      summary: Get Attribute by Internal Name
      description: Retrieve attribute using internal name
      operationId: getAttrByNameNm
      parameters:
      - name: entityNm
        in: path
        required: true
        schema:
          type: string
      - name: nameNm
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attr'
            application/xml:
              schema:
                $ref: '#/components/schemas/Attr'
  /attr/{attrId}:
    get:
      summary: Get Attribute
      description: Retrieve atribute using Id
      operationId: getAttrById
      parameters:
      - name: attrId
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/DtUid'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attr'
            application/xml:
              schema:
                $ref: '#/components/schemas/Attr'
  /domain/{domainNm}:
    get:
      summary: Get Domain by Internal Name
      description: Retrieve domain using internal name
      operationId: getDomainByNameNm
      parameters:
      - name: domainNm
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
            application/xml:
              schema:
                $ref: '#/components/schemas/Domain'
  /domain:
    get:
      summary: Get All Domains
      description: Retrieve all domains
      operationId: getAllDomains
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
  /domain/{domainId}:
    get:
      summary: Get Domain
      description: Retrieve domain using Id
      operationId: getDomainById
      parameters:
      - name: domainId
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/DtUid'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
            application/xml:
              schema:
                $ref: '#/components/schemas/Domain'
  /entity/{entityNm}:
    get:
      summary: Get Entity by Internal Name
      description: Retrieve entity using internal name
      operationId: getEntityByNameNm
      parameters:
      - name: entityNm
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
            application/xml:
              schema:
                $ref: '#/components/schemas/Entity'
  /entity/{entityId}:
    get:
      summary: Get Entity
      description: Retrieve entity using Id
      operationId: getEntityByNameNm_1
      parameters:
      - name: entityId
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/DtUid'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
            application/xml:
              schema:
                $ref: '#/components/schemas/Entity'
components:
  schemas:
    Attr:
      type: object
      properties:
        ordInEntity:
          type: integer
          format: int32
        name:
          type: string
        readOnly:
          type: boolean
        ordered:
          type: boolean
        entity:
          $ref: '#/components/schemas/Entity'
        setOtherOpTypeId:
          $ref: '#/components/schemas/DtUid'
        fromObjectFormula:
          $ref: '#/components/schemas/Attr'
        accDocObjectFormulaId:
          $ref: '#/components/schemas/DtUid'
        fromObjectFormulaId:
          $ref: '#/components/schemas/DtUid'
        accDocObjectFormula:
          $ref: '#/components/schemas/Attr'
        toObjectFormulaId:
          $ref: '#/components/schemas/DtUid'
        mandatory:
          type: boolean
        hierarchical:
          type: boolean
        isqVisible:
          type: boolean
        nameNm:
          type: string
        textSrc:
          $ref: '#/components/schemas/Attr'
        subdomainNm:
          type: string
        indexed:
          type: boolean
        logAllowed:
          type: boolean
        resetOpTypeId:
          $ref: '#/components/schemas/DtUid'
        properNameRoot:
          type: string
        attrGrp:
          $ref: '#/components/schemas/AttrGrp'
        multiCreate:
          type: boolean
        isOwn:
          type: boolean
        getOpTypeId:
          $ref: '#/components/schemas/DtUid'
        setOpTypeId:
          $ref: '#/components/schemas/DtUid'
        dictType:
          type: string
        isInTable:
          type: boolean
        genMove:
          type: boolean
        getlLength:
          type: number
          format: double
        upNameNm:
          type: string
        domain:
          $ref: '#/components/schemas/Domain'
        entityId:
          $ref: '#/components/schemas/DtUid'
        attrGrpId:
          $ref: '#/components/schemas/DtUid'
        logLevel:
          type: string
        note:
          type: string
        attrType:
          type: string
        isCustom:
          type: boolean
        isUsed:
          type: boolean
        ord:
          type: number
          format: double
        defValue:
          type: string
        textSrcId:
          $ref: '#/components/schemas/DtUid'
        validated:
          type: boolean
        multivalue:
          type: boolean
        ordGroup:
          type: string
        dictDel1:
          type: string
        domainId:
          $ref: '#/components/schemas/DtUid'
        tbCodeCd:
          type: string
        ownerFormula:
          $ref: '#/components/schemas/Attr'
        toObjectFormula:
          $ref: '#/components/schemas/Attr'
        confirmOther:
          type: boolean
        approxRecord:
          type: boolean
        genCopy:
          type: boolean
        dictDel2:
          type: string
        valueAccountNm:
          type: string
        accountRuleNm:
          type: string
        ownerFormulaId:
          $ref: '#/components/schemas/DtUid'
        genDelete:
          type: boolean
        fileServerId:
          $ref: '#/components/schemas/DtUid'
        imgHeight:
          type: number
          format: double
        getxIsFlagDepBind:
          type: string
        imgSrcId:
          $ref: '#/components/schemas/DtUid'
        keyOrd:
          type: number
          format: double
        manLobLimit:
          type: number
          format: double
        copied:
          type: string
        opTypeTypeRf:
          $ref: '#/components/schemas/DtUid'
        evalCValue:
          type: boolean
        optLobLimit:
          type: number
          format: double
        documentation:
          type: string
        bitmapOrd:
          type: integer
          format: int32
        valueAmountType:
          type: string
        isxIsFlagDefAttr:
          type: boolean
        imgWidth:
          type: number
          format: double
        defOwner:
          type: boolean
        imgSrc:
          $ref: '#/components/schemas/Attr'
        genMigr:
          type: boolean
        id:
          $ref: '#/components/schemas/DtUid'
    AttrGrp:
      type: object
      properties:
        attrs:
          type: array
          items:
            $ref: '#/components/schemas/Attr'
        name:
          type: string
        entity:
          $ref: '#/components/schemas/Entity'
        nameNm:
          type: string
        entityId:
          $ref: '#/components/schemas/DtUid'
        note:
          type: string
        isCustom:
          type: boolean
        ord:
          type: integer
          format: int32
        id:
          $ref: '#/components/schemas/DtUid'
    Domain:
      type: object
      properties:
        name:
          type: string
        dataLength:
          type: integer
          format: int32
        validateCd:
          type: string
        getlFormatCd:
          type: string
        natOrder:
          type: boolean
        allowed:
          type: boolean
        islVisible:
          type: boolean
        dataTypeNm:
          type: string
        dataPrecision:
          type: integer
          format: int32
        isqVisible:
          type: boolean
        note:
          type: string
        nameNm:
          type: string
        id:
          $ref: '#/components/schemas/DtUid'
    DtUid:
      type: object
      properties:
        value:
          type: integer
        multiline:
          type: boolean
        priv:
          type: boolean
        me:
          type: boolean
        regular:
          type: boolean
    Entity:
      type: object
      properties:
        attrGrps:
          type: array
          items:
            $ref: '#/components/schemas/AttrGrp'
        attrs:
          type: array
          items:
            $ref: '#/components/schemas/Attr'
        name:
          type: string
        ancestor:
          $ref: '#/components/schemas/Entity'
        getxFlagDefInterest0:
          type: number
          format: double
        getxFlagDefInterest1:
          type: number
          format: double
        getxFlagDefInterest2:
          type: number
          format: double
        getxFlagDefInterest3:
          type: number
          format: double
        getxFlagDefInterest4:
          type: number
          format: double
        getxFlagDefInterest5:
          type: number
          format: double
        isxHasDelRowFlagDef:
          type: boolean
        textTableNm:
          type: string
        textKeyNm:
          type: string
        textAll:
          type: boolean
        pgPackageNm:
          type: string
        confObj:
          type: string
        viewNm:
          type: string
        keyNm:
          type: string
        properName:
          type: string
        textViewNm:
          type: string
        epPackageNm:
          type: string
        userLockType:
          type: string
        objectClass:
          type: boolean
        tableNm:
          type: string
        masterId:
          $ref: '#/components/schemas/DtUid'
        masterType:
          type: string
        cpPackageNm:
          type: string
        importType:
          type: string
        fpPackageNm:
          type: string
        basePath:
          type: string
        incompleteKey:
          type: boolean
        entityGrp:
          $ref: '#/components/schemas/EntityGrp'
        ancestorId:
          $ref: '#/components/schemas/DtUid'
        confObjAll:
          type: boolean
        entityGrpId:
          $ref: '#/components/schemas/DtUid'
        customNote:
          type: string
        usageDoc:
          type: string
        behaviourDoc:
          type: string
        implDoc:
          type: string
        getRightCustom:
          type: boolean
        getRightRestrId:
          $ref: '#/components/schemas/DtUid'
        structureDoc:
          type: string
        longDesc:
          type: string
        getxCopiedAttr2:
          type: number
          format: double
        useConfObj:
          type: boolean
        getxDelNotifyAttr1:
          type: number
          format: double
        getxDelNotifyAttr3:
          type: number
          format: double
        getxNotifyAttr2:
          type: number
          format: double
        getxDelNotifyAttr4:
          type: number
          format: double
        getxCopiedAttr3:
          type: number
          format: double
        getxCopiedAttr5:
          type: number
          format: double
        getxDelNotifyAttr0:
          type: number
          format: double
        getxNotifyAttr3:
          type: number
          format: double
        getxNotifyAttr4:
          type: number
          format: double
        getxDelNotifyAttr2:
          type: number
          format: double
        getxNotifyAttr5:
          type: number
          format: double
        getxCopiedAttr1:
          type: number
          format: double
        isxHasLiability:
          type: boolean
        getxUseConfObj:
          type: boolean
        getxNotifyAttr0:
          type: number
          format: double
        getxNotifyAttr1:
          type: number
          format: double
        getxDelNotifyAttr5:
          type: number
          format: double
        shortDesc:
          type: string
        getxCopiedAttr0:
          type: number
          format: double
        keepDeleted:
          type: integer
          format: int32
        getxCopiedAttr4:
          type: number
          format: double
        getOpTypeId:
          $ref: '#/components/schemas/DtUid'
        note:
          type: string
        isCustom:
          type: boolean
        isUsed:
          type: boolean
        nameNm:
          type: string
        id:
          $ref: '#/components/schemas/DtUid'
    EntityGrp:
      type: object
      properties:
        children:
          type: array
          items:
            $ref: '#/components/schemas/EntityGrp'
        entities:
          type: array
          items:
            $ref: '#/components/schemas/Entity'
        fullOrd:
          type: array
          items:
            type: integer
            format: int32
        name:
          type: string
        note:
          type: string
        ord:
          type: integer
          format: int32
        parentId:
          $ref: '#/components/schemas/DtUid'
        nameNm:
          type: string
        id:
          $ref: '#/components/schemas/DtUid'
