/*
 * This file is generated by jOOQ.
 */
package com.provys.catalogue.dbloader.db.tables.records;


import com.provys.catalogue.dbloader.db.tables.KerAttrgrpTb;

import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KerAttrgrpTbRecord extends UpdatableRecordImpl<KerAttrgrpTbRecord> implements Record7<BigInteger, BigInteger, String, String, String, Integer, String> {

    private static final long serialVersionUID = 169845374;

    /**
     * Setter for <code>KER.KER_ATTRGRP_TB.ATTRGRP_ID</code>.
     */
    public void setAttrgrpId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>KER.KER_ATTRGRP_TB.ATTRGRP_ID</code>.
     */
    public BigInteger getAttrgrpId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>KER.KER_ATTRGRP_TB.ENTITY_ID</code>.
     */
    public void setEntityId(BigInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>KER.KER_ATTRGRP_TB.ENTITY_ID</code>.
     */
    public BigInteger getEntityId() {
        return (BigInteger) get(1);
    }

    /**
     * Setter for <code>KER.KER_ATTRGRP_TB.ISCUSTOM</code>.
     */
    public void setIscustom(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>KER.KER_ATTRGRP_TB.ISCUSTOM</code>.
     */
    public String getIscustom() {
        return (String) get(2);
    }

    /**
     * Setter for <code>KER.KER_ATTRGRP_TB.NAME_NM</code>. Internal name of attribute group
     */
    public void setNameNm(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>KER.KER_ATTRGRP_TB.NAME_NM</code>. Internal name of attribute group
     */
    public String getNameNm() {
        return (String) get(3);
    }

    /**
     * Setter for <code>KER.KER_ATTRGRP_TB.NAME</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>KER.KER_ATTRGRP_TB.NAME</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>KER.KER_ATTRGRP_TB.ORD</code>.
     */
    public void setOrd(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>KER.KER_ATTRGRP_TB.ORD</code>.
     */
    public Integer getOrd() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>KER.KER_ATTRGRP_TB.NOTE</code>. Notes regarding attributes in group and their usage
     */
    public void setNote(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>KER.KER_ATTRGRP_TB.NOTE</code>. Notes regarding attributes in group and their usage
     */
    public String getNote() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<BigInteger, BigInteger, String, String, String, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<BigInteger, BigInteger, String, String, String, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field1() {
        return KerAttrgrpTb.KER_ATTRGRP_TB.ATTRGRP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field2() {
        return KerAttrgrpTb.KER_ATTRGRP_TB.ENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return KerAttrgrpTb.KER_ATTRGRP_TB.ISCUSTOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return KerAttrgrpTb.KER_ATTRGRP_TB.NAME_NM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return KerAttrgrpTb.KER_ATTRGRP_TB.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return KerAttrgrpTb.KER_ATTRGRP_TB.ORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return KerAttrgrpTb.KER_ATTRGRP_TB.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component1() {
        return getAttrgrpId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component2() {
        return getEntityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIscustom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getNameNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getOrd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value1() {
        return getAttrgrpId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value2() {
        return getEntityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIscustom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNameNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getOrd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerAttrgrpTbRecord value1(BigInteger value) {
        setAttrgrpId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerAttrgrpTbRecord value2(BigInteger value) {
        setEntityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerAttrgrpTbRecord value3(String value) {
        setIscustom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerAttrgrpTbRecord value4(String value) {
        setNameNm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerAttrgrpTbRecord value5(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerAttrgrpTbRecord value6(Integer value) {
        setOrd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerAttrgrpTbRecord value7(String value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerAttrgrpTbRecord values(BigInteger value1, BigInteger value2, String value3, String value4, String value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KerAttrgrpTbRecord
     */
    public KerAttrgrpTbRecord() {
        super(KerAttrgrpTb.KER_ATTRGRP_TB);
    }

    /**
     * Create a detached, initialised KerAttrgrpTbRecord
     */
    public KerAttrgrpTbRecord(BigInteger attrgrpId, BigInteger entityId, String iscustom, String nameNm, String name, Integer ord, String note) {
        super(KerAttrgrpTb.KER_ATTRGRP_TB);

        set(0, attrgrpId);
        set(1, entityId);
        set(2, iscustom);
        set(3, nameNm);
        set(4, name);
        set(5, ord);
        set(6, note);
    }
}
