/*
 * This file is generated by jOOQ.
 */
package com.provys.catalogue.dbloader.db.tables.records;


import com.provys.catalogue.dbloader.db.tables.KerEntitygrpTb;

import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Entity group
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KerEntitygrpTbRecord extends UpdatableRecordImpl<KerEntitygrpTbRecord> implements Record7<BigInteger, BigInteger, String, String, String, String, Integer> {

    private static final long serialVersionUID = 1961782281;

    /**
     * Setter for <code>KER.KER_ENTITYGRP_TB.ENTITYGRP_ID</code>. UID
     */
    public void setEntitygrpId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>KER.KER_ENTITYGRP_TB.ENTITYGRP_ID</code>. UID
     */
    public BigInteger getEntitygrpId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>KER.KER_ENTITYGRP_TB.PARENT_ID</code>. Parent group
     */
    public void setParentId(BigInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>KER.KER_ENTITYGRP_TB.PARENT_ID</code>. Parent group
     */
    public BigInteger getParentId() {
        return (BigInteger) get(1);
    }

    /**
     * Setter for <code>KER.KER_ENTITYGRP_TB.NAME_NM</code>. Internal name
     */
    public void setNameNm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>KER.KER_ENTITYGRP_TB.NAME_NM</code>. Internal name
     */
    public String getNameNm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>KER.KER_ENTITYGRP_TB.NAME</code>. Name of group; translated as NLSNAME
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>KER.KER_ENTITYGRP_TB.NAME</code>. Name of group; translated as NLSNAME
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>KER.KER_ENTITYGRP_TB.X_UPNAME</code>. Calculated column - uppercase of NAME
     */
    public void setXUpname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>KER.KER_ENTITYGRP_TB.X_UPNAME</code>. Calculated column - uppercase of NAME
     */
    public String getXUpname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>KER.KER_ENTITYGRP_TB.NOTE</code>. Short description; translated as NLSNOTE
     */
    public void setNote(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>KER.KER_ENTITYGRP_TB.NOTE</code>. Short description; translated as NLSNOTE
     */
    public String getNote() {
        return (String) get(5);
    }

    /**
     * Setter for <code>KER.KER_ENTITYGRP_TB.ORD</code>. Ordering of entity groups within their parent / absolute; items with same ORD are sorted using name
     */
    public void setOrd(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>KER.KER_ENTITYGRP_TB.ORD</code>. Ordering of entity groups within their parent / absolute; items with same ORD are sorted using name
     */
    public Integer getOrd() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<BigInteger, BigInteger, String, String, String, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<BigInteger, BigInteger, String, String, String, String, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field1() {
        return KerEntitygrpTb.KER_ENTITYGRP_TB.ENTITYGRP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field2() {
        return KerEntitygrpTb.KER_ENTITYGRP_TB.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return KerEntitygrpTb.KER_ENTITYGRP_TB.NAME_NM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return KerEntitygrpTb.KER_ENTITYGRP_TB.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return KerEntitygrpTb.KER_ENTITYGRP_TB.X_UPNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return KerEntitygrpTb.KER_ENTITYGRP_TB.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return KerEntitygrpTb.KER_ENTITYGRP_TB.ORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component1() {
        return getEntitygrpId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component2() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNameNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getXUpname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getOrd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value1() {
        return getEntitygrpId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value2() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNameNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getXUpname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getOrd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerEntitygrpTbRecord value1(BigInteger value) {
        setEntitygrpId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerEntitygrpTbRecord value2(BigInteger value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerEntitygrpTbRecord value3(String value) {
        setNameNm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerEntitygrpTbRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerEntitygrpTbRecord value5(String value) {
        setXUpname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerEntitygrpTbRecord value6(String value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerEntitygrpTbRecord value7(Integer value) {
        setOrd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerEntitygrpTbRecord values(BigInteger value1, BigInteger value2, String value3, String value4, String value5, String value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KerEntitygrpTbRecord
     */
    public KerEntitygrpTbRecord() {
        super(KerEntitygrpTb.KER_ENTITYGRP_TB);
    }

    /**
     * Create a detached, initialised KerEntitygrpTbRecord
     */
    public KerEntitygrpTbRecord(BigInteger entitygrpId, BigInteger parentId, String nameNm, String name, String xUpname, String note, Integer ord) {
        super(KerEntitygrpTb.KER_ENTITYGRP_TB);

        set(0, entitygrpId);
        set(1, parentId);
        set(2, nameNm);
        set(3, name);
        set(4, xUpname);
        set(5, note);
        set(6, ord);
    }
}
